### PR TITLE
add eslint-config-prettier

### PR DESCRIPTION
**Pull request by JamesDowney**
If I left something out or messed things up, please let me know!

### CODE REVIEW

**Review by gausie — APPROVED** [review]
I think that's right. Did you try it out?

**Comment by gausie** [comment]
> I think that's right. Did you try it out?

The reason I ask is that I might have expected some more additions to the yarn.lock file around eslint version pinning.

**Comment by JamesDowney** [comment]
> > I think that's right. Did you try it out?
> 
> The reason I ask is that I might have expected some more additions to the yarn.lock file around eslint version pinning.

I've since bumped up eslint and the libram plugin and let the yarn.lock file update appropriately. Just now tested it locally and itgenerated a new script with `eslint-config-prettier` included as expected, the script built and linted as expected as well.

**Comment by gausie** [comment]
So the key thing here is that we want a first install not to change the
yarn.lock, that's sort of the point of the file

**Pull request merged**
